feat: Allow the RW API endpoint URL to be set (via Ansible) by using dependency injection.
UN-OCHA/response-site pull request #839
Opened 2024-10-31 05:58 UTC by cafuego

Refs: OPS-10807

2024-10-31 06:14 UTC, cafuego commented
See https://github.com/UN-OCHA/tools-ansible/pull/1484/commits/9838bfd9419bdeaeda454cc12711a8f3e4b856b9

2024-10-31 23:16 UTC, orakili requested changes

2024-10-31 23:16 UTC, orakili commented on config/hr_paragraphs.settings.yml
> +reliefweb_api_endpoint: 'https://api.reliefweb.int/v1/reports'
Missing `reliefweb_api_appname`.

Also those 2 new properties need to be added to the schema: https://github.com/UN-OCHA/response-site/blob/develop/html/modules/custom/hr_paragraphs/config/schema/hr_paragraphs.schema.yml

And should be added there as well: https://github.com/UN-OCHA/response-site/blob/develop/html/modules/custom/hr_paragraphs/config/install/hr_paragraphs.settings.yml

2024-10-31 23:16 UTC, orakili commented on html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php
> +class ReliefwebController extends ControllerBase implements ContainerInjectionInterface {
ControllerBase already implements `ContainerInjectionInterface` so this is not needed.

2024-11-05 11:16 UTC, attiks approved these changes

2024-11-08 07:01 UTC, orakili approved these changes

2024-11-15 00:50 UTC, merged